spring.application.name=pagination-filtre
spring.datasource.url=jdbc:mysql://localhost:3306/crud-springboot 
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Niveau global
logging.level.root=INFO

# Logs Spring
logging.level.org.springframework=INFO

# Logs de ton projet
logging.level.com.dp.pagination_filtre=DEBUG

# Sauvegarde dans un fichier
logging.file.name=app.log